services:
  - type: web
    name: deepfake-resnet152-explainable
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: ENV
        value: production